<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<ProjectReference Include="$(berger-open-source)\Berger.Extensions.Abstractions\src\Berger.Extensions.Abstractions\Berger.Extensions.Abstractions.csproj" />
		<ProjectReference Include="$(berger-open-source)\Berger.Extensions.Configuration\src\Berger.Extensions.Configuration\Berger.Extensions.Configuration.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
	</ItemGroup>
</Project>