<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<ProjectReference Include="$(berger-open-source)\Berger.Extensions.Abstractions\src\Berger.Extensions.Abstractions\Berger.Extensions.Abstractions.csproj" />
		<ProjectReference Include="$(berger-open-source)\Berger.Extensions.Configuration\src\Berger.Extensions.Configuration\Berger.Extensions.Configuration.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<PackageReference Include="Berger.Extensions.Abstractions" Version="1.0.0.*" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>
</Project>